image:
  repository: alexeyya/go-userauth-microservices
  tag: "latest"
  pullPolicy: IfNotPresent

authService:
  image:
    repository: auth-service-image
    tag: "latest"
  replicaCount: 1
  port: 8080

userService:
  image:
    repository: user-service-image
    tag: "latest"
  replicaCount: 1
  port: 8081

gatewayService:
  image:
    repository: gateway-service-image
    tag: "latest"
  replicaCount: 1
  port: 8082

postgres:
  image: postgres:16-alpine
  username: auth_user
  password: auth_pass
  database: auth_db
  port: 5432
  storage:
    size: 1Gi