{{- if .Values.jwt.secretValue }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "go-userauth-microservices.fullname" . }}-secrets
  labels:
    {{- include "go-userauth-microservices.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ .Values.jwt.secretValue | b64enc }}
{{- end }}
